#ifndef APP_POWER_CONFIG_H
#define APP_POWER_CONFIG_H

#define APP_POWER_ADC_SAMPLE_PERIOD_MS 1U
#define APP_POWER_SETTLEMENT_PERIOD_MS 100U
#define APP_POWER_ADC_REFERENCE_MV    3300U
#define APP_POWER_BUS_VOLTAGE_MV     11980U
#define APP_POWER_LIMIT_ENABLE          0U
#define APP_POWER_BUFFER_ENABLE         0U
#define APP_POWER_LIMIT_W              28U
#define APP_POWER_BUFFER_MAX_DECI_J   200U
#define APP_POWER_CUT_DURATION_MS    5000U
#define APP_POWER_ADC_MAX_CONSECUTIVE_FAILURES 3U
#define APP_POWER_CURRENT_LIMIT_MA   4000U
#define APP_POWER_OVERCURRENT_DURATION_MS 200U
#define APP_POWER_APPLICATION_LIMIT_MAX_W 1000U
#define APP_POWER_CURRENT_LIMIT_MAX_MA 16500U
#define APP_POWER_MEASUREMENT_WARNING_W 160U

#endif /* APP_POWER_CONFIG_H */
