#ifndef APP_POWER_CONFIG_H
#define APP_POWER_CONFIG_H

#define APP_POWER_ADC_SAMPLE_PERIOD_MS 1U
#define APP_POWER_WINDOW_SAMPLES       100U
#define APP_POWER_ADC_REFERENCE_MV    3300U
#define APP_POWER_BUS_VOLTAGE_MV     11980U
#define APP_POWER_LIMIT_W               0U

#endif /* APP_POWER_CONFIG_H */
